<?php
function request($url, $post = null, $cookies = null, $headers = null)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    curl_setopt($ch, CURLOPT_HEADER, 1);
    if(!is_null($headers))
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    if(!is_null($cookies))
        curl_setopt($ch, CURLOPT_COOKIE, $cookies);
    if(!is_null($post)){
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    }
    $resp = curl_exec($ch);
    $header_len = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $header = substr($resp, 0, $header_len);
    $body = substr($resp, $header_len);
    curl_close($ch);
    preg_match_all('#Set-Cookie: ([^;]+)#', $header, $d);
    $cookie = '';
    for ($o=0;$o<count($d[0]);$o++) {
        $cookie.=$d[1][$o].";";
    }

    return [$header, $body, $cookie];
}

function getName()
{
    $names = array(
        'Diyan',
        'Indah',
        'Dani',
        'Putra',
        'Rohmat',
        'Sarah',
        'Agustina',
        'Joko',
        'Cahaya',
        'Cinta',
        'Tedjo',
        'Ade',
        'Putri',
        'Pranoto',
        'Haliman',
        'Lanfen',
        'Sugondo',
        'Dandan',
        'Kabeera',
        'Salampessy',
        'Esther',
        'Beringin',
        'Beulah',
        'Jadibata',
        'Selah',
        'Berasa',
        'Megawati',
        'Eko',
        'Bima',
        'Hadiman',
        'Sudomo',
        'Dian',
        'Tedja',
        'Iskandar',
        'Siyu',
        'Anggriawan',
        'Xiaosi',
        'Maaiz',
        'Faud',
        'Nathan',
        'Rumasingap',
        'Manasseh',
        'Bunuhaji',
        'Aquila',
        'Pasaribu',
        'Sriwidadi',
        'Bima',
        'Bambang',
        'Gunardi',
        'Santoso',
        'Longwei',
        'Limijanti',
        'Xiaojian',
        'Idrees',
        'Malawat',
        'Levi',
        'Siampapaga',
        'Rufus',
        'Pane',
        'Onesimus',
        'Ginting',
        'Suripto',
        'Guntur',
        'Dwi',
        'Dian',
        'Tedjo',
        'Teguh',
        'Hendri',
        'Kartawijaya',
        'Canggih',
        'Chongkun',
        'Jayawan',
        'Yi',
        'Floriaan',
        'Manusama',
        'Baruch',
        'Sinabalok',
        'Adonijah',
        'Cambo',
        'Tobiah',
        'Larosa',
        'Slamet',
        'Sriwidadi',
        'Ary',
        'Herman',
        'Hermanto',
        'Budi',
        'Surya',
        'Indrajaya',
        'Setio',
        'Zhìxin',
        'Wono',
        'Lì',
        'Faaris',
        'Teterissa',
        'Asa',
        'Tinendung',
        'Noah',
        'Pelawi',
        'Melchizedek',
        'Lumbantoruan',
        'Sukarto',
        'Bambang',
        'Eka',
        'Bima',
        'Darmadi',
        'Sonny',
        'Iwan',
        'Hadiman',
        'Jayawan',
        'Yang',
        'Stephoan',
        'Chao',
        'Nikolai',
        'Nahumarury',
        'Amos',
        'Rumapea',
        'Moses',
        'Parhusip',
        'Reuben',
        'Namohaji',
        'Raharjo',
        'Sukarto',
        'Sonny',
        'Tirta',
        'Kusnadi',
        'Hengki',
        'Johan',
        'Johan',
        'Wendi',
        'Lì',
        'Inyo',
        'Xin',
        'Saamir',
        'Baadilla',
        'Habakkuk',
        'Zebua',
        'Manasseh',
        'Simarsoit',
        'Ishmael',
        'Simorangkir',
        'Raharjo',
        'Susilo',
        'Ari',
        'Hendri',
        'Setiabudi',
        'Ridwan',
        'Dian',
        'Kartawijaya',
        'Alim',
        'Renshu',
        'Lumenta',
        'Ping',
        'Nigel',
        'Angwarmasse',
        'Onesimus',
        'Sinubulan',
        'Obadiah',
        'Kacaribu',
        'Isaiah',
        'Simarsoit',
        'Sukarno',
        'Sutikno',
        'Purnama',
        'Tirto',
        'Lesmono',
        'Ary',
        'Hadi',
        'Budiman',
        'Chandrawinata',
        'Shing',
        'Juanita',
        'Jian',
        'Reimert',
        'Tahapary',
        'Paul',
        'Gerneng',
        'Eleazar',
        'Maliam',
        'Ithamar',
        'Bangun',
        'Adi',
        'Suharto',
        'Susanti',
        'Cahya',
        'Kusuma',
        'Glenna',
        'Farida',
        'Tahyadi',
        'Teddy',
        'Ninghong',
        'Sugondo',
        'Meixiu',
        'Kifaaya',
        'Marasabessy',
        'Susannah',
        'Tamba',
        'Atarah',
        'Pandia',
        'Abishai',
        'Sihaloho',
        'Suminten',
        'Sinta',
        'Susanti',
        'Hartanti',
        'Oesman',
        'Mega',
        'Dwi',
        'Pranata',
        'Sutanto',
        'Shun',
        'Setiadi',
        'Eu-fùnh',
        'Kylie',
        'Latuperissa',
        'Huldah',
        'Lembong',
        'Jochebed',
        'Hutasuhut',
        'Ophrah',
        'Marbun',
        'Tuminindyah',
        'Eko',
        'Ida',
        'Iman',
        'Cahyadi',
        'Yulia',
        'Eka',
        'Irawan',
        'Aliwarga',
        'Ju',
        'Baroleh',
        'Yanyu',
        'Isabella',
        'Matrutty',
        'Tamar',
        'Rumahorbo',
        'Tirzah',
        'Silali',
        'Rose',
        'Porti',
        'Dwi',
        'Surtinem',
        'Widyawati',
        'Bulan',
        'Budiman',
        'Verawati',
        'Citra',
        'Halim',
        'Widjaja',
        'Ya',
        'Tanasal',
        'Biyu',
        'Shivani',
        'Oost',
        'Neriah',
        'Tinambunan',
        'Tirzah',
        'Situngkir',
        'Mara',
        'Simatupang',
        'Lestari',
        'Srilestari'
    );
    $random_name = $names[mt_rand(0, sizeof($names) - 1)];
    return $random_name;
}

function getSurname()
{
    $surnames = array(
        'Wahyu',
        'Bima',
        'Hadiman',
        'Sudomo',
        'Dian',
        'Tedja',
        'Iskandar',
        'Siyu',
        'Anggriawan',
        'Xiaosi',
        'Maaiz',
        'Faud',
        'Nathan',
        'Rumasingap',
        'Manasseh',
        'Bunuhaji',
        'Aquila',
        'Pasaribu',
        'Sriwidadi',
        'Bambang',
        'Indah',
        'Dani',
        'Putra',
        'Rohmat',
        'Sarah',
        'Agustina',
        'Joko',
        'Cahaya',
        'Cinta',
        'Tedjo',
        'Ade',
        'Putri',
        'Pranoto',
        'Haliman',
        'Lanfen',
        'Sugondo',
        'Dandan',
        'Kabeera',
        'Salampessy',
        'Esther',
        'Beringin',
        'Beulah',
        'Jadibata',
        'Selah',
        'Berasa',
        'Megawati',
        'Eko',
        'Bambang',
        'Gunardi',
        'Santoso',
        'Longwei',
        'Limijanti',
        'Xiaojian',
        'Idrees',
        'Malawat',
        'Levi',
        'Siampapaga',
        'Rufus',
        'Pane',
        'Onesimus',
        'Ginting',
        'Suripto',
        'Guntur',
        'Dwi',
        'Dian',
        'Tedjo',
        'Teguh',
        'Hendri',
        'Kartawijaya',
        'Canggih',
        'Chongkun',
        'Jayawan',
        'Yi',
        'Floriaan',
        'Manusama',
        'Baruch',
        'Sinabalok',
        'Adonijah',
        'Cambo',
        'Tobiah',
        'Larosa',
        'Slamet',
        'Sriwidadi',
        'Ary',
        'Herman',
        'Hermanto',
        'Budi',
        'Surya',
        'Indrajaya',
        'Setio',
        'Zhìxin',
        'Wono',
        'Lì',
        'Faaris',
        'Teterissa',
        'Asa',
        'Tinendung',
        'Noah',
        'Pelawi',
        'Melchizedek',
        'Lumbantoruan',
        'Sukarto',
        'Bambang',
        'Eka',
        'Bima',
        'Darmadi',
        'Sonny',
        'Iwan',
        'Hadiman',
        'Jayawan',
        'Yang',
        'Stephoan',
        'Chao',
        'Nikolai',
        'Nahumarury',
        'Amos',
        'Rumapea',
        'Moses',
        'Parhusip',
        'Reuben',
        'Namohaji',
        'Raharjo',
        'Sukarto',
        'Sonny',
        'Tirta',
        'Kusnadi',
        'Hengki',
        'Johan',
        'Johan',
        'Wendi',
        'Lì',
        'Inyo',
        'Xin',
        'Saamir',
        'Baadilla',
        'Habakkuk',
        'Zebua',
        'Manasseh',
        'Simarsoit',
        'Ishmael',
        'Simorangkir',
        'Raharjo',
        'Susilo',
        'Ari',
        'Hendri',
        'Setiabudi',
        'Ridwan',
        'Dian',
        'Kartawijaya',
        'Alim',
        'Renshu',
        'Lumenta',
        'Ping',
        'Nigel',
        'Angwarmasse',
        'Onesimus',
        'Sinubulan',
        'Obadiah',
        'Kacaribu',
        'Isaiah',
        'Simarsoit',
        'Sukarno',
        'Sutikno',
        'Purnama',
        'Tirto',
        'Lesmono',
        'Ary',
        'Hadi',
        'Budiman',
        'Chandrawinata',
        'Shing',
        'Juanita',
        'Jian',
        'Reimert',
        'Tahapary',
        'Paul',
        'Gerneng',
        'Eleazar',
        'Maliam',
        'Ithamar',
        'Bangun',
        'Adi',
        'Suharto',
        'Susanti',
        'Cahya',
        'Kusuma',
        'Glenna',
        'Farida',
        'Tahyadi',
        'Teddy',
        'Ninghong',
        'Sugondo',
        'Meixiu',
        'Kifaaya',
        'Marasabessy',
        'Susannah',
        'Tamba',
        'Atarah',
        'Pandia',
        'Abishai',
        'Sihaloho',
        'Suminten',
        'Sinta',
        'Susanti',
        'Hartanti',
        'Oesman',
        'Mega',
        'Dwi',
        'Pranata',
        'Sutanto',
        'Shun',
        'Setiadi',
        'Eu-fùnh',
        'Kylie',
        'Latuperissa',
        'Huldah',
        'Lembong',
        'Jochebed',
        'Hutasuhut',
        'Ophrah',
        'Marbun',
        'Tuminindyah',
        'Eko',
        'Ida',
        'Iman',
        'Cahyadi',
        'Yulia',
        'Eka',
        'Irawan',
        'Aliwarga',
        'Ju',
        'Baroleh',
        'Yanyu',
        'Isabella',
        'Matrutty',
        'Tamar',
        'Rumahorbo',
        'Tirzah',
        'Silali',
        'Rose',
        'Porti',
        'Dwi',
        'Surtinem',
        'Widyawati',
        'Bulan',
        'Budiman',
        'Verawati',
        'Citra',
        'Halim',
        'Widjaja',
        'Ya',
        'Tanasal',
        'Biyu',
        'Shivani',
        'Oost',
        'Neriah',
        'Tinambunan',
        'Tirzah',
        'Situngkir',
        'Mara',
        'Simatupang',
        'Lestari',
        'Srilestari'
    );
    $random_surname = $surnames[mt_rand(0, sizeof($surnames) - 1)];
    return $random_surname;
}

function randomPassword($length = 7) {
    $characters = 'qwertyuioipasdfghjklzxcvbnm0123456789';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}

function getRandom($length = 7) {
    $characters = '0123456789';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}

$header = array(
    'Accept: application/json, text/plain, */*',
    'Accept-Language: en-US,en;q=0.5',
    'Referer: https://primexbt.com/',
    'Content-Type: application/json;charset=utf-8',
    'Origin: https://primexbt.com',
    'Connection: keep-alive',
    'TE: Trailers'
);

$tt = array("@gmail.com", "@yahoo.com", "@yahoo.co.id", "@ymail.com");

echo 'Mau berapa akun tuyul lur? ';
$jumlah = trim(fgets(STDIN));
for($i = 1; $i <= $jumlah; $i++) {
    $namad = getName();
    $namab = getSurname();
    $number = getRandom();
    $nama = $namad.' '.$namab;
    $email = $namad.$namab.$number.$tt[rand(0, 3)];
    $url = 'https://app.viral-loops.com/api/v2/events';
    $data = '{"apiToken":"qyJgvPS6CQ51tffYJ3NPzMy9Klg","params":{"event":"registration","user":{"firstname":"'.$nama.'","email":"'.$email.'"},"referrer":{"referralCode":"f57aN1h"},"refSource":"copy"}}';
    $daftar = request($url, $data, null, $header);
    echo $daftar[1].PHP_EOL;
}
?>